name: pstream-docs

services:
  docs:
    image: ghcr.io/okikio/mov-docs:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SITE_URL=${SITE_URL:-https://xp-technologies-dev.github.io}
        - BASE_PATH=${BASE_PATH:-/pstream-docs}
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped
